version: '3.8'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    ports:
      - '0:8000'
    volumes:
      - './:/var/www/html'
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=whatever
      - DB_USERNAME=root
      - DB_PASSWORD=Aziz2022@
    depends_on:
      - mysql
    networks:
      - app-network
  vue:
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - '0:80'
    volumes:
      - './frontend:/app'
    networks:
      - app-network
  mysql:
    image: 'mysql:8.0'
    ports:
      - '0:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=Aziz2022@
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=Aziz2022@
    networks:
      - app-network
volumes:
  mysql-data: null
networks:
  app-network:
    driver: bridge
